package Dreamer.enums;

public enum Status {
	INITIALIZED, 
	DEAD, 
	RIGHT, TRYRIGHT, 
	LEFT, TRYLEFT,
	JUMPING, TRYJUMP, GROUNDED,
	ATTACKING, TRYATTACK,
	BLOCKING, 
	TRYSPRINT, SPRINTING, 
	SWEATING, 
	DAMAGED, 
	CLIMBING, DOWN, UP, 
	ACTING
}
